export type Formation = {
  slug: string;
  titre: string;
  img: string;
  duree: string;
  cpf: boolean;
  kit: boolean;
  categorie: string;
  description: string;
  detail: string;
};

export type Prestation = {
  titre: string;
  img: string;
  prix: string;
  description: string;
};

export const formations: Formation[] = [
  {
    slug: "microblading",
    titre: "Microblading",
    img: "/imara/soins/blading-shading.jpg",
    duree: "2 jours",
    cpf: true,
    kit: true,
    categorie: "Pigmentation",
    description: "Tracé poil à poil pour des sourcils naturels et définis.",
    detail: "Apprenez la technique du microblading, l'art du tracé poil à poil pour recréer des sourcils naturels et parfaitement définis. Formation intensive combinant théorie pigmentaire, pratique sur supports et suivi post-formation.",
  },
  {
    slug: "microshading",
    titre: "Microshading",
    img: "/imara/soins/blading-shading.jpg",
    duree: "2 jours",
    cpf: true,
    kit: true,
    categorie: "Pigmentation",
    description: "Effet poudré naturel, complément idéal au microblading.",
    detail: "Le microshading crée un effet poudré doux et naturel. Technique complémentaire au microblading, idéale pour les peaux mixtes à grasses. Inclut la maîtrise des dégradés et des densités pigmentaires.",
  },
  {
    slug: "microblading-microshading",
    titre: "Microblading + Microshading",
    img: "/imara/soins/blading-shading.jpg",
    duree: "3 jours",
    cpf: true,
    kit: true,
    categorie: "Pigmentation",
    description: "Combo complet : tracé poil à poil + effet poudré.",
    detail: "Formation combinée microblading et microshading pour maîtriser les deux techniques en une seule session. La formation la plus complète pour proposer une offre sourcils exhaustive à vos clients.",
  },
  {
    slug: "extension-cils-classique",
    titre: "Extension de Cils",
    img: "/imara/soins/extensions-mixte.jpg",
    duree: "2 jours",
    cpf: true,
    kit: true,
    categorie: "Regard",
    description: "Pose classique et Volume Russe. Maîtrise complète des extensions.",
    detail: "Apprenez les techniques fondamentales des extensions de cils : pose mixte, volume naturel et density. Formation axée sur la précision du geste, le choix des extensions selon la morphologie et la fidélisation client.",
  },
  {
    slug: "extension-cils-volume-russe",
    titre: "Extension de Cils — Volume Russe",
    img: "/imara/soins/extensions-volume-russe.jpg",
    duree: "2 jours",
    cpf: true,
    kit: true,
    categorie: "Regard",
    description: "Technique avancée du Volume Russe pour un effet XXL.",
    detail: "Maîtrisez la technique du Volume Russe, bouquets de 2 à 6 cils ultrafins par cil naturel. Formation avancée pour professionnelles déjà formées aux extensions classiques. Résultats spectaculaires et durables.",
  },
  {
    slug: "rehaussement-cils",
    titre: "Réhaussement · Teinture · Lash Botox",
    img: "/imara/soins/extensions-mixte.jpg",
    duree: "1-2 jours",
    cpf: true,
    kit: true,
    categorie: "Regard",
    description: "Sublimer les cils naturels sans extensions.",
    detail: "Trio de techniques pour sublimer les cils naturels : réhaussement de cils (lift), teinture et Lash Botox pour nourrir et fortifier. Alternative aux extensions, très demandée par les clientes allergiques ou qui veulent un look naturel.",
  },
  {
    slug: "browlift",
    titre: "Browlift",
    img: "/imara/soins/blading-shading.jpg",
    duree: "1 jour",
    cpf: true,
    kit: true,
    categorie: "Regard",
    description: "Technique de lissage et mise en forme des sourcils.",
    detail: "Le Browlift discipline et redresse les poils de sourcils pour un effet lifting immédiat. Combiné à une teinture, il transforme le regard sans maquillage. Formation rapide et très rentable.",
  },
  {
    slug: "epilation-fil",
    titre: "Épilation au Fil",
    img: "/imara/soins/eye-liner-classique.jpg",
    duree: "1-2 jours",
    cpf: true,
    kit: true,
    categorie: "Regard",
    description: "Technique ancestrale de précision pour sourcils et visage.",
    detail: "L'épilation au fil est une technique ancestrale d'une précision incomparable. Formation incluant la prise en main du fil, les techniques sourcils et visage, la gestion de la douleur et les contre-indications.",
  },
  {
    slug: "epilation-fil-teinture",
    titre: "Épilation au Fil · Teinture",
    img: "/imara/soins/eye-liner-classique.jpg",
    duree: "2 jours",
    cpf: true,
    kit: true,
    categorie: "Regard",
    description: "Épilation au fil + teinture sourcils pour un résultat complet.",
    detail: "Combo épilation au fil et teinture des sourcils pour proposer une prestation complète reshape + couleur. Formation incluant la colorimétrie, le choix des teintes selon le phototype et les protocoles d'application.",
  },
  {
    slug: "epilation-fil-browlift-teinture",
    titre: "Épilation au Fil · Browlift · Teinture",
    img: "/imara/soins/eye-liner-classique.jpg",
    duree: "2 jours",
    cpf: true,
    kit: true,
    categorie: "Regard",
    description: "Prestation sourcils complète en une formation.",
    detail: "La formation sourcils la plus complète : épilation au fil + browlift + teinture. Maîtrisez l'intégralité de la prestation sourcils pour vous positionner comme experte regard.",
  },
  {
    slug: "eye-liner-permanent",
    titre: "Eye Liner Permanent",
    img: "/imara/soins/eye-liner-3d.jpeg",
    duree: "1-2 jours",
    cpf: true,
    kit: true,
    categorie: "Pigmentation",
    description: "Tracé permanent classique ou 3D effet poudré.",
    detail: "Apprenez à réaliser l'eye liner permanent en technique classique et effet poudré 3D. Formation incluant l'anatomie de l'œil, les tracés adaptés aux morphologies et la gestion des risques.",
  },
  {
    slug: "imara-lips",
    titre: "Imara Lips",
    img: "/imara/soins/imara-lips.jpg",
    duree: "1-2 jours",
    cpf: true,
    kit: true,
    categorie: "Pigmentation",
    description: "Tatouage lèvres semi-permanent, technique exclusive Imara.",
    detail: "Maîtrisez la technique Imara Lips pour des lèvres pulpeuses et définies en permanence. Formation incluant la définition du contour, le remplissage, le choix des pigments selon le phototype et les retouches.",
  },
  {
    slug: "headspa",
    titre: "HeadSpa",
    img: "/imara/spa.jpg",
    duree: "1 jour",
    cpf: false,
    kit: true,
    categorie: "Bien-être",
    description: "Soin capillaire japonais — massage et rituels du cuir chevelu.",
    detail: "Le HeadSpa est le rituel capillaire japonais alliant massage du cuir chevelu, soins profonds et relaxation totale. Formation incluant les techniques de massage, les protocoles de soins et l'expérience client.",
  },
  {
    slug: "hydrimara",
    titre: "Hydr'Imara",
    img: "/imara/soins/imara-gold-visage.jpeg",
    duree: "1 jour",
    cpf: false,
    kit: true,
    categorie: "Visage",
    description: "Protocole soin visage hydratation intense, technique Imara.",
    detail: "Hydr'Imara est le protocole soin visage signature de l'Institut. Formation incluant l'analyse de peau, les techniques d'application, les actifs utilisés et la personnalisation du soin selon le type cutané.",
  },
  {
    slug: "maquillage",
    titre: "Maquillage",
    img: "/imara/soins/eye-liner-classique.jpg",
    duree: "1-2 jours",
    cpf: false,
    kit: true,
    categorie: "Maquillage",
    description: "Techniques de maquillage professionnel — jour, soirée, événement.",
    detail: "Formation maquillage professionnel couvrant les techniques jour, soirée et événement. Apprenez la correction des imperfections, la mise en valeur des traits, et la création de looks adaptés à chaque morphologie.",
  },
  {
    slug: "auto-maquillage",
    titre: "Auto-Maquillage",
    img: "/imara/soins/eye-liner-classique.jpg",
    duree: "1 jour",
    cpf: false,
    kit: false,
    categorie: "Maquillage",
    description: "Apprenez à vous maquiller seule — techniques et astuces pro.",
    detail: "Cours individuel ou en petit groupe pour apprendre à se maquiller selon sa morphologie, son teint et ses envies. Idéal pour proposer des ateliers à votre clientèle. Formation valorisante et génératrice de fidélité.",
  },
  {
    slug: "maquillage-mariee",
    titre: "Maquillage Mariée",
    img: "/imara/soins/eye-liner-classique.jpg",
    duree: "1-2 jours",
    cpf: false,
    kit: true,
    categorie: "Maquillage",
    description: "Spécialisation maquillage de mariage — durabilité et émotion.",
    detail: "Spécialisez-vous dans le maquillage mariée, une niche premium très demandée. Formation incluant les techniques longue tenue, les essais, la gestion du stress client et les looks tendance pour mariages.",
  },
  {
    slug: "blanchiment-dentaire",
    titre: "Blanchiment Dentaire",
    img: "/imara/soins/imara-lips.jpg",
    duree: "1 jour",
    cpf: false,
    kit: true,
    categorie: "Médico-esthétique",
    description: "Technique de blanchiment dentaire esthétique non invasive.",
    detail: "Formation au blanchiment dentaire esthétique avec lampe LED. Apprenez les protocoles, les contre-indications, la réglementation en vigueur et les techniques de communication pour proposer cette prestation premium.",
  },
  {
    slug: "strass-dentaire",
    titre: "Strass Dentaire",
    img: "/imara/soins/imara-lips.jpg",
    duree: "0,5 jour",
    cpf: false,
    kit: true,
    categorie: "Médico-esthétique",
    description: "Application de strass sur dents — tendance et précision.",
    detail: "Application de cristaux décoratifs sur les dents avec résine dentaire. Prestation tendance et accessible, idéale en add-on. Formation incluant les protocoles d'hygiène, les matériaux et les techniques d'application.",
  },
  {
    slug: "piercing",
    titre: "Piercing",
    img: "/imara/spa.jpg",
    duree: "1 jour",
    cpf: false,
    kit: true,
    categorie: "Médico-esthétique",
    description: "Techniques et protocoles de piercing esthétique.",
    detail: "Formation piercing incluant l'anatomie des zones de percage, les protocoles d'hygiène et stérilisation, les types de bijoux, les soins post-piercing et la réglementation. Pratique incluse sur supports synthétiques.",
  },
  {
    slug: "hygiene-salubrite",
    titre: "Hygiène et Salubrité",
    img: "/imara/spa.jpg",
    duree: "1 jour",
    cpf: false,
    kit: false,
    categorie: "Réglementaire",
    description: "Formation obligatoire agréée ARS — obligatoire pour ouvrir votre institut.",
    detail: "Formation réglementaire obligatoire agréée par l'Agence Régionale de Santé. Indispensable pour exercer en tant que professionnelle de la beauté. Couvre les règles d'hygiène, les protocoles de désinfection et la législation en vigueur.",
  },
];

export const prestations: Prestation[] = [
  {
    titre: "Extensions de Cils — Pose Mixte",
    img: "/imara/soins/extensions-mixte.jpg",
    prix: "100€",
    description: "Regard transformé, durée 3-4 semaines.",
  },
  {
    titre: "Extensions de Cils — Volume Russe",
    img: "/imara/soins/extensions-volume-russe.jpg",
    prix: "120€",
    description: "Effet XXL et dense, ultra léger.",
  },
  {
    titre: "L'Imara — Microblading & Shading",
    img: "/imara/soins/blading-shading.jpg",
    prix: "290€",
    description: "Sourcils naturels et définis, durée 12-18 mois.",
  },
  {
    titre: "Imara Lips",
    img: "/imara/soins/imara-lips.jpg",
    prix: "250€",
    description: "Lèvres définies et pulpeuses en permanence.",
  },
  {
    titre: "Eye Liner 3D — Effet poudré",
    img: "/imara/soins/eye-liner-3d.jpeg",
    prix: "230€",
    description: "Regard intense sans effort quotidien.",
  },
  {
    titre: "Eye Liner Classique",
    img: "/imara/soins/eye-liner-classique.jpg",
    prix: "210€",
    description: "Tracé précis et durable.",
  },
  {
    titre: "Imara Gold — Visage",
    img: "/imara/soins/imara-gold-visage.jpeg",
    prix: "255€ (pack 3)",
    description: "Radiofréquence anti-âge haute technologie.",
  },
  {
    titre: "Lumière Pulsée",
    img: "/imara/soins/lumiere-pulsee.jpeg",
    prix: "770€",
    description: "Épilation longue durée, grande zone.",
  },
];

export function getFormationBySlug(slug: string): Formation | undefined {
  return formations.find((f) => f.slug === slug);
}

export const categories = [...new Set(formations.map((f) => f.categorie))];
